version: '3'
services:
  gitlab-hooks-service:
    image: frendwong/gitlab-hooks-service:v1.0.0
    deploy:
      replicas: 5
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
    ports:
     - "3420:3420"
